version: "2"
services:
################################################################################
##                                    Jackett                                 ##
################################################################################
jackett:
  image: linuxserver/jackett
  container_name: jackett
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Rome
    - UMASK_SET=022 #optional
  volumes:
    - jackett_data:/config
    - jackett_data:/downloads
  ports:
    - 9117:9117
  restart: unless-stopped
################################################################################
##                                    Sonarr                                  ##
################################################################################
sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - UMASK_SET=022 #optional
    volumes:
      - sonarr_data:/config
      - /media/spawn5m/Media/Plex/Tv\ Show/:/tv
      - /media/spawn5m/Media/Download/:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
