version: "2"
services:

################################################################################
##                                  Deluge                                    ##
################################################################################
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error
    volumes:
      - deluge_data:/config
      - /media/spawn5m/Media/Download/:/downloads
    ports:
      - 8112:8112
    restart: unless-stopped

################################################################################
##                                    Jackett                                 ##
################################################################################
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - UMASK_SET=022 #optional
    volumes:
      - jackett_data:/config
      - jackett_data:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

################################################################################
##                                    Sonarr                                  ##
################################################################################
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - UMASK_SET=022 #optional
    volumes:
      - sonarr_data:/config
      - /media/spawn5m/Media/Plex/TvShow/:/tv
      - /media/spawn5m/Media/Download/:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

################################################################################
##                                 Radarr                                     ##
################################################################################
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - UMASK_SET=022 #optional
    volumes:
      - radarr_data:/config
      - /media/spawn5m/Media/Plex/Movie/:/movies
      - /media/spawn5m/Media/Download/:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

################################################################################
##                                    Bazarr                                 ##
################################################################################
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - UMASK_SET=022 #optional
    volumes:
      -  bazarr_data:/config
      - /media/spawn5m/Media/Plex/Movie/:/movies
      - /media/spawn5m/Media/Plex/TvShow/:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

################################################################################
##                                    PLEX                                    ##
################################################################################
  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=claim-DQoyUjzQ6xKsN1HLx9qk
    volumes:
      - pms_data:/config
      - /home/spawn5m/DockerConfig/PMS_Data/:/transcode
      - /media/spawn5m/Media/Plex/:/data
    ports:
      - 32400:32400
    restart: unless-stopped

################################################################################
##                                 Netatalk                                   ##
################################################################################

  netatalk:
    image: cptactionhank/netatalk:latest
    container_name: netatalk
    environment:
      - AFP_USER=spawn5m
      - AFP_PASSWORD=maggigul
      - AFP_UID=1000
      - AFP_GID=1000
      - AVAHI=1
    network_mode: host
    volumes:
      - /home/spawn5m/DockerConfig/Netatalk_Data/etc/afp.conf:/etc/afp.conf
      - /media/spawn5m/Media/:/media/share
      - /media/spawn5m/Backup/TimeMachine/:/media/timemachine
    restart: unless-stopped


################################################################################
##                                 Calibre                                    ##
################################################################################
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - GUAC_USER=spawn5m #optional
      - GUAC_PASS=8dd893f052dc4918275b955a65285750 #optional
    volumes:
      - calibre_data:/config
      - /media/spawn5m/Media/Books/Calibre/Book/:/books
      - /media/spawn5m/Media/Books/Calibre/Pass/:/CalibreStore
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped


################################################################################
##                             lazylibrarian                                  ##
################################################################################
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - lazylibrarian_data:/config
      - /media/spawn5m/Media/Books/LazyLibrarian/Download/:/downloads
      - /media/spawn5m/Media/Books/LazyLibrarian/Book/:/books
    ports:
      - 5299:5299
    restart: unless-stopped

################################################################################
##                                 Heimdall                                   ##
################################################################################
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - heimdall_data:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
